//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC12.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventManagerCNC
    {
        public int Id { get; set; }
        public int IdCNC { get; set; }
        public int IdHienTrangMayCNC { get; set; }
        public int IdHienTrangCuaMayCNC { get; set; }
        public string Ngay { get; set; }
        public string ThoiDiem { get; set; }
    
        public virtual MachinesCNC MachinesCNC { get; set; }
        public virtual HienTrangCuaMayCNC HienTrangCuaMayCNC { get; set; }
        public virtual HienTrangMayCNC HienTrangMayCNC { get; set; }
    }
}
