//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC12.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerCNCEntities : DbContext
    {
        public ManagerCNCEntities()
            : base("name=ManagerCNCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoTriCuaMayCNC> BaoTriCuaMayCNCs { get; set; }
        public virtual DbSet<CaLamViec> CaLamViecs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<EventManagerCNC> EventManagerCNCs { get; set; }
        public virtual DbSet<HienTrangCuaMayCNC> HienTrangCuaMayCNCs { get; set; }
        public virtual DbSet<HienTrangMayCNC> HienTrangMayCNCs { get; set; }
        public virtual DbSet<MachinesCNC> MachinesCNCs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
